// qiankun/monorepo-micro-app-root-test-main/sub-apps/vitest-vue3-ts-el-app/src/views/home/index.vue
<script setup lang="ts">
// import HelloWorld from '@/components/HelloWorld.vue'
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="@/assets/images/svg/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <p>test</p>
  </div>
  <!-- <HelloWorld msg="Vite + Vue" /> -->
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// qiankun/monorepo-micro-app-root-test-main/main-apps/vitest-react-ts-swc-base/src/views/home/index.tsx
import { useState } from 'react';
import reactLogo from '@/assets/images/svg/react.svg';
import viteLogo from '/vite.svg';

function Home() {
	const [count, setCount] = useState(0);

	return (
		<div className="main-wrapper">
			<div className="App">
				<a
					href="https://vitejs.dev"
					target="_blank"
				>
					<img
						src={viteLogo}
						className="logo"
						alt="Vite logo"
					/>
				</a>
				<a
					href="https://react.dev"
					target="_blank"
				>
					<img
						src={reactLogo}
						className="logo react"
						alt="React logo"
					/>
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button onClick={() => setCount(count => count + 1)}>count is {count}</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">Click on the Vite and React logos to learn more</p>
		</div>
	);
}

export default Home;
